add blog feature
coopdevs/coopdevs-old-web pull request #1
Opened 2018-04-13 13:13 UTC by sseerrggii

2018-04-13 16:56 UTC, sauloperez requested changes
I would like to see an screenshot if possible

2018-04-13 16:56 UTC, sauloperez commented on _layouts/post.html
> +</div>
Can we use less indentation? I won't fees on my laptop's screen soon :trollface:

2018-04-16 07:47 UTC, sseerrggii commented
![peek 16-04-2018 09-44](https://user-images.githubusercontent.com/2297137/38796201-f1756bc0-415a-11e8-985b-155a8e4f0e73.gif)

2018-04-16 07:54 UTC, sauloperez commented
I think that background image will make it a bit difficult to read the blog posts. I would simply leave a white background.

2018-04-19 09:43 UTC, enricostano requested changes

2018-04-19 09:43 UTC, enricostano commented on _includes/header.html
> +    </div>
Fix indentation and add newline

2018-04-19 09:43 UTC, enricostano commented on _posts/2018-04-12-first-post.md
> +Post de prova.
Nos acordaremos de quitar los posts de prueba? :joy:

2018-04-19 09:50 UTC, sseerrggii commented on _posts/2018-04-12-first-post.md
> +Post de prova.
si, hay que preparar algún artículo antes de sacar el blog

2018-04-25 07:41 UTC, sseerrggii commented
El primer post ja està en el PR, canvieu el que calgui i... :boom:
He afegit bootstrap per fer més fàcil la creació de continguts

![peek 25-04-2018 09-41](https://user-images.githubusercontent.com/2297137/39232224-de99c15e-486c-11e8-8500-a4617b185299.gif)

2018-04-25 08:00 UTC, sauloperez requested changes

2018-04-25 08:00 UTC, sauloperez commented on _posts/2018-04-24-Por-fin-llegamos-A-la-casilla-de-salida.md
> +Muy pocas personas son conscientes del coste que representa desarrollar, mantener y mejorar una plataforma digital, no solo se trata de hacer un código que funcione y ponerlo en un servidor, las plat
Noto muchas comas que se usan como punto. Que tal `(...) mantener y mejorar una plataforma digital. No solo se trata de hacer un código que funcione y ponerlo en un servidor. Las plataformas digitales requieren una atención constante, si hay (...) que no puede recaer solamente en los técnicos sino que debe ser asumida por la comunidad que usa la plataforma. En este sentido nos esperanza el modelo (...)`?

2018-04-25 08:00 UTC, sauloperez commented on _posts/2018-04-24-Por-fin-llegamos-A-la-casilla-de-salida.md
> +Lo fácil sería sumarse al carro de las subvenciones. Es fantástico que la financiación pública se vuelque en proyectos cooperativos y de claro impacto social, pero hay que ir con cuidado con el efect
s/impulsen el que fas/impulsem el que fas

2018-04-25 08:00 UTC, sauloperez commented on _posts/2018-04-24-Por-fin-llegamos-A-la-casilla-de-salida.md
> +Katuma y TimeOverflow son proyectos que hemos emprendido desde cero, hemos desarrollado las plataformas confiando en que encontraremos la manera de sostenerlas. Podríamos embarcarnos en un tercer pro
Que te parece `Katuma y TimeOverflow son proyectos que hemos emprendido desde cero. Hemos desarrollado (...)`?

2018-04-25 08:00 UTC, sauloperez commented on _posts/2018-04-24-Por-fin-llegamos-A-la-casilla-de-salida.md
> +Katuma y TimeOverflow son proyectos que hemos emprendido desde cero, hemos desarrollado las plataformas confiando en que encontraremos la manera de sostenerlas. Podríamos embarcarnos en un tercer pro
Escribiría siempre Coopdevs con c mayúscula por consistencia y por ser un nombre propio.

2018-04-25 08:05 UTC, sauloperez requested changes

2018-04-25 08:05 UTC, sauloperez commented on _posts/2018-04-24-Por-fin-llegamos-A-la-casilla-de-salida.md
> +A principios de 2018 creamos la cooperativa de treball coopdevs treball sccl, el brazo profesionalizado de Coopdevs. Esto nos dota de otra herramienta más, la asociación Coopdevs es el núcleo de nues
Para evitar la redundancia escribiria `(...) cooperative Coopdevs treball SCCL`.

2018-04-25 08:05 UTC, sauloperez commented on _posts/2018-04-24-Por-fin-llegamos-A-la-casilla-de-salida.md
> +A principios de 2018 creamos la cooperativa de treball coopdevs treball sccl, el brazo profesionalizado de Coopdevs. Esto nos dota de otra herramienta más, la asociación Coopdevs es el núcleo de nues
`Esto nos dota de otra herramienta más. La asociación Coopdevs es el núcleo de nuestras actividades y todos nuestros proyectos se impulsan desde su asamblea. Con esto queremos que se acerquen personas de diferentes perfiles (...). Para ello vemos claro que necesitamos profesionales dedicados a tiempo completo (...).

2018-04-26 07:16 UTC, sauloperez approved these changes

2018-04-26 10:55 UTC, sauloperez requested changes

2018-04-26 10:55 UTC, sauloperez commented on _posts/2018-04-24-Por-fin-llegamos-A-la-casilla-de-salida.md
> +### Pero si es sotware libre ¿no cuesta dinero no?
`(...) dinero, no?` no? :trollface:

2018-04-26 11:08 UTC, enricostano approved these changes

2018-04-26 11:09 UTC, sauloperez commented on _posts/2018-04-24-Por-fin-llegamos-A-la-casilla-de-salida.md
> +### Pero si es software libre ¿no cuesta dinero no?
`(...) dinero, no?` no? :trollface:

2018-04-26 11:10 UTC, sauloperez approved these changes

2018-04-26 11:12 UTC, merged