Bootstrap migration
coopdevs/coopdevs-old-web pull request #10
Opened 2018-05-01 08:53 UTC by sseerrggii

Añadí bootstrap para facilitar la escritura de los artículos en https://github.com/coopdevs/coopdevs.github.io/pull/1 ahora he hecho cambios para añadirlo a toda la web y facilitar que se vea bien en todos los dispositivos

![peek 01-05-2018 10-45](https://user-images.githubusercontent.com/2297137/39467276-8cfc1b42-4d2d-11e8-9808-919945c070fd.gif)

2018-05-02 10:52 UTC, sauloperez requested changes

2018-05-02 10:52 UTC, sauloperez commented on _includes/footer.html
> +</div>
Por qué estos 3 divs?

2018-05-02 10:52 UTC, sauloperez commented on _includes/header.html
> +				<p>{{ page.description_2 | markdownify }}</p>
por favor, configura tu editor para que introduzca 4 espacios y no tabs :pray: . Dificulta bastante la lectura y a la que se complique el layout con más divs se nos va a ir de madre.

2018-05-02 12:02 UTC, sauloperez requested changes

2018-05-02 12:02 UTC, sauloperez commented on _layouts/post.html
>  	<header>
please, update the indentation as well.

2018-05-02 12:02 UTC, sauloperez commented on _includes/header.html
> +            </div>
Sorry, I noticed the existing files were using 2 spaces instead of 4. We need to stick to it on all files of this PR.

2018-05-02 13:09 UTC, sseerrggii commented on _includes/footer.html
> +</div>
son para cerrar los que se abren en header

2018-05-02 13:30 UTC, sauloperez requested changes

2018-05-02 13:30 UTC, sauloperez commented on _includes/footer.html
> +</div>
why these divs?

2018-05-02 13:30 UTC, sauloperez commented on _includes/section.html
> +{%- assign _photo = '' -%}
but now you removed all the indentation in some places and that wasn't the point :sweat_smile:

2018-05-10 07:33 UTC, sseerrggii commented on _includes/footer.html
> +</div>
close divs opened in header.html

<div class="container-fluid">
    <div class="row">
        <div class='mx-auto col-12 col-sm-10 col-md-8'>

2018-05-10 07:35 UTC, sauloperez approved these changes

2018-05-10 07:42 UTC, merged