Add new blog post about coopdevs and platform cooperativism
coopdevs/coopdevs-old-web pull request #21
Opened 2018-06-13 09:33 UTC by sseerrggii

2018-06-13 11:24 UTC, danypr92 approved these changes

2018-06-16 06:37 UTC, sseerrggii commented
@enricostano @sauloperez can you review the blog post text? :pray:

2018-06-18 12:55 UTC, sauloperez requested changes

2018-06-18 12:55 UTC, sauloperez commented on _posts/2018-06-13-cooperativisme-de-plataforma.md
> +En l’era digital, cada vegada són més les grans companyies que es fan perillosament poderoses amb una plataforma online: Amazon, Facebook, Google, Netflix, Airbnb, Uber,.. Donen servei a centenars de
"(...) treballadores de la plataforma, per (...)" :point_right: "(...) treballadores de la plataforma. Per (...)"

2018-06-18 12:55 UTC, sauloperez commented on _posts/2018-06-13-cooperativisme-de-plataforma.md
> +En l’era digital, cada vegada són més les grans companyies que es fan perillosament poderoses amb una plataforma online: Amazon, Facebook, Google, Netflix, Airbnb, Uber,.. Donen servei a centenars de
a més de "el rol de treballador" jo afegiria alguna referència a les condicions laborals com "saltant-se tota legislació laboral amb la connivència dels estats que cedeixen al xantatge d'aquestes transnacionals". Potser s'hauria de reformular amb l'última frase del paràgraf.

2018-06-18 12:55 UTC, sauloperez commented on _posts/2018-06-13-cooperativisme-de-plataforma.md
> +En definitiva, aquests nous imperis en forma de plataformes digitals, tenen un gran impacte en la vida de les persones. La gran qüestió és si és possible trobar models on les persones que fan ús de l
"telecomunicacions, les persones" :point_right: "telecomunicacions. Les persones"

2018-06-18 12:55 UTC, sauloperez commented on _posts/2018-06-13-cooperativisme-de-plataforma.md
> +En definitiva, aquests nous imperis en forma de plataformes digitals, tenen un gran impacte en la vida de les persones. La gran qüestió és si és possible trobar models on les persones que fan ús de l
Canviaria "en són copropietàries de les mateixes empreses que els ofereixen els serveis." per "en són copropietàries.". Em sembla redundant.

2018-06-18 12:55 UTC, sauloperez commented on _posts/2018-06-13-cooperativisme-de-plataforma.md
> +A Coopdevs participem a diferents plataformes amb una clara intenció: que les seves usuàries en siguin les principals gestores i propietàries. Coopdevs participa com una sòcia més, que aporta princip
"com una sòcia més, que aporta principalment els mitjans tècnics" ho reformularia per "com una sòcia més, aportant principalment els mitjans tècnics i de disseny de plataformes"

2018-06-18 12:55 UTC, sauloperez commented on _posts/2018-06-13-cooperativisme-de-plataforma.md
> +Internament, les sòcies de Coopdevs, decidim en quins projectes ens involucrem. Tots els projectes en que participem tenen un mínim comú denominador: son open source i aporten solucions per a l’econo
"son open source" :point_right: "són open source"

2018-06-18 12:55 UTC, sauloperez commented on _posts/2018-06-13-cooperativisme-de-plataforma.md
> +Cada plataforma en què participem ha de tenir una entitat jurídica: cooperativa o associació, on les usuàries de la plataforma estiguin representades, aquesta fórmula atorga la sobirania de la plataf
"representades, aquesta" :point_right: "representades. Aquesta"

2018-06-18 12:55 UTC, sauloperez commented on _posts/2018-06-13-cooperativisme-de-plataforma.md
> +En el cas de la plataforma [Katuma](http://katuma.org/) el projecte open source és: [Open Food Network](https://openfoodnetwork.org/), diferents països tenen diferents plataformes funcionant amb Open
Crec que els dos punts de "open source és:" sobren en aquest cas.

2018-06-18 12:55 UTC, sauloperez commented on _posts/2018-06-13-cooperativisme-de-plataforma.md
> +En el cas de la plataforma [Katuma](http://katuma.org/) el projecte open source és: [Open Food Network](https://openfoodnetwork.org/), diferents països tenen diferents plataformes funcionant amb Open
", diferents països" :point_right: ". Diferents països"

2018-06-18 12:55 UTC, sauloperez commented on _posts/2018-06-13-cooperativisme-de-plataforma.md
> +Katuma està en vies de constituir-se com a cooperativa de serveis, on Coopdevs és sols una actora més, el pes principal de la cooperativa recau sobre els grups de consum i productores que fan ús de l
"Katuma està en vies de constituir-se com a cooperativa de serveis, on Coopdevs és sols una actora més, el pes principal de la cooperativa recau sobre els grups de consum i productores que fan ús de la plataforma. " :point_right: "Katuma està en vies de constituir-se com a cooperativa de serveis, on Coopdevs és sols una actora més. El pes principal de la cooperativa recau sobre els grups de consum i productores que fan ús de la plataforma. "

2018-06-18 12:55 UTC, sauloperez commented on _posts/2018-06-13-cooperativisme-de-plataforma.md
> +Si bé Katuma com entitat és autònoma en les seves decisions, ha de tenir molt en compte tota la comunitat internacional d’Open Food Network. Imaginem que pel que fos Katuma i la comunitat internacion
Canviaria "Imaginem que pel que fos Katuma i la comunitat internacional Open Food Network no es posessin d’acord en com ha de funcionar la plataforma. Katuma hauria de seguir el seu propi camí en solitari amb els costos afegits que implicaria no compartir el desenvolupament amb la comunitat internacional d’Open Food Network. " per "En l'hipotètic cas que katuma tingués desacords amb Open Food Network, Katuma hauria de seguir el seu propi cami en solitari, assumint els costos d'haver de portar a terme el desenvolupament de la plataforma sense la cooperació d'Open Food Network."

2018-06-18 12:55 UTC, sauloperez commented on _posts/2018-06-13-cooperativisme-de-plataforma.md
> +La complexitat és important, el repte és important, però l’objectiu s’ho mereix!!
Escriuria "La complexitat és gran" per evitar la redundància.

2018-06-18 12:55 UTC, sauloperez commented
Bon article @sseerrggii !

2018-06-19 07:02 UTC, sseerrggii commented
Thank you very much @sauloperez for your meticulous review, all your suggestions seemed good to me.

Respecte el capitalisme... espero el teu article :smiling_imp: Jo he fet una passada per sobre per intentar no polititzar molt la opinió i simplement descriure la realitat que tenim i les solucions que proposa el cooperativisme de plataforma.

![giphy-downsized](https://user-images.githubusercontent.com/2297137/41581596-4663ee9c-739f-11e8-8f11-1a6bc2664050.gif)

2018-06-19 11:49 UTC, sauloperez approved these changes

2018-07-23 08:31 UTC, enricostano approved these changes
Maybe I would add a link to the Alba Hierro new article in La Directa. For the rest... 😍

2018-07-23 18:24 UTC, sseerrggii commented
Thanks @enricostano 

I added link to la Directa article, change de publish date and delete the image of platformcoop book because now is a list of a related reads.

2018-07-24 11:56 UTC, merged