Update location address
coopdevs/coopdevs-old-web pull request #46
Opened 2019-02-13 20:38 UTC by naoisegolden

Remove Espai 30 and add Coworking Nogués

2019-02-13 21:52 UTC, sauloperez approved these changes

2019-02-13 21:52 UTC, sauloperez commented on _i18n/ca.yml
> +    description_2: "Si voleu col·laborar amb nosaltres ens podeu trobar a <a href='http://community.coopdevs.org'>community.coopdevs.org</a> i a <a href='https://github.com/coopdevs'>github.com/coopd
Lol I didn't know they had a website

2019-02-14 19:29 UTC, enricostano requested changes

2019-02-14 19:29 UTC, enricostano commented on _i18n/ca.yml
> +    description_2: "Si voleu col·laborar amb nosaltres ens podeu trobar a <a href='http://community.coopdevs.org'>community.coopdevs.org</a> i a <a href='https://github.com/coopdevs'>github.com/coopd
`de la Sagrera.` no :joy:

2019-02-15 12:33 UTC, sauloperez approved these changes

2019-02-15 15:17 UTC, merged