New post: Construyendo comunidades Open Source en la ESS
coopdevs/coopdevs-old-web pull request #47
Opened 2019-03-06 17:23 UTC by sseerrggii

![fireshot capture 195 - coopdevs_ - http___localhost_4000_2019_03_06_c](https://user-images.githubusercontent.com/2297137/53900451-dbb81300-403c-11e9-8788-fa9ef7c11749.png)

2019-03-13 18:24 UTC, sauloperez requested changes
En general em sembla molt bé. És un molt bon pont de partida per un tema que dóna per molts blog posts. I a més m'agrada el to del text. Felicitats @sseerrggii !

2019-03-13 18:24 UTC, sauloperez commented on _i18n/ca/_posts/2019-03-06-contruyendo-comunidades-open-source.md
> +Si bien es cierto que en el mundo cooperativista no hay un gran número de cooperativas del sector IT (tecnología de la información) esta tendencia está cambiando. Desde nuestra perspectiva es un buen
i si afegim algo com "Desde el cooperativismo para el cooperativismo" al final per remarcar la idea?

2019-03-13 18:24 UTC, sauloperez commented on _i18n/ca/_posts/2019-03-06-contruyendo-comunidades-open-source.md
> +Sabemos que no lo dices en serio ;) Volviendo al ejemplo de la receta, aunque compartas la receta nadie va a prepararla igual que tú, vas a notar mucha diferencia entre la misma receta preparada por
no se on pot cabre però crec que també és molt interessant la idea de que si deixes que algú faci la seva propia versió de la recepta a partir de la teva, molt probablement li donarà un toc diferent que tu no havies valorat i que beneficiarà als dos. Si no li comparteixes la recepta no dones oportunitat a que et sorprenguin i enriqueixin.

2019-03-13 18:24 UTC, sauloperez commented on _i18n/ca/_posts/2019-03-06-contruyendo-comunidades-open-source.md
> +En Coopdevs participamos en varias comunidades Open Source, entre ellas destacan [Open Food Network (Katuma.org)](https://openfoodnetwork.net/) y [TimeOverflow](https://www.timeoverflow.org/). Acompa
A això li faltaria un títol que el separés del `Todo el mundo podrá ver los agujeros de seguridad y atacarme.` sinó sembla un paràgraf de la mateixa secció i causarà confusió. A mi sempre em passa el mateix 🙈

2019-03-13 18:24 UTC, sauloperez commented on _i18n/ca/_posts/2019-03-06-contruyendo-comunidades-open-source.md
> +Si quieres conocer más sobre comunidades Open Source te recomendamos leer [https://opensource.guide/es/](https://opensource.guide/es/)
ep, ara veig que aquest és suposadament el text en català. No oblidem traduïr-lo quan en tinguem una versió final.

2019-03-14 15:26 UTC, sseerrggii commented
Thanks @sauloperez for your suggestions I pushed changes

2019-03-14 15:27 UTC, sseerrggii commented on _i18n/ca/_posts/2019-03-06-contruyendo-comunidades-open-source.md
> +Si quieres conocer más sobre comunidades Open Source te recomendamos leer [https://opensource.guide/es/](https://opensource.guide/es/)
Ara els articles els tenin a es i ca pero sols els tenim en un idioma. Es algo a discutir, jo crec que no val la pena traduir els articles, es millora anar fent en diverses llengües i deixar-les en aquella llengüa. Només traduiria la part més estàtica de la Web

2019-03-27 07:00 UTC, sseerrggii commented
Merge o que onda? @danypr92 @enricostano @sauloperez 

![giphy (3)](https://user-images.githubusercontent.com/2297137/55056412-58e80e00-5066-11e9-8a7a-3b68b7834a98.gif)

2019-03-28 10:47 UTC, sauloperez commented
S'ha de traduir al català encara ⚠️

2019-03-28 10:48 UTC, sauloperez requested changes
S'ha de traduir al català encara ⚠️ la resta em sembla bé.

2019-03-28 10:58 UTC, sseerrggii commented
@sauloperez com et vaig dir https://github.com/coopdevs/coopdevs.github.io/pull/47#discussion_r265626269 no tenim cap article publicat traduit

2019-04-03 16:00 UTC, sauloperez commented
Llavors volem mostrar el mateix contingut en tots els idiomes? O amagar-lo? Si optem pel primer així està bé

2019-04-03 16:33 UTC, sseerrggii commented
De moment el mostrem igual el tots els idiomes.

2019-04-03 16:55 UTC, sauloperez approved these changes

2019-04-07 07:09 UTC, sseerrggii commented
Un mes hauria de ser suficient per llegir-nos....
Merge? 

@sauloperez @enricostano @danypr92

2019-04-09 09:02 UTC, merged

2019-04-10 10:02 UTC, enricostano commented
Me gustaria tener mas tiempo para leer estas propuestas sinceramente, no tenemos prisa de publicar.